services:
  db:
    image: postgres:16-alpine
    container_name: tienda_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecr3tPassWord@as2
      POSTGRES_DB: tienda_dbt
    ports:
      - "5432:5432"
    volumes:
      - tienda_pgdata:/var/lib/postgresql/data

volumes:
  tienda_pgdata:
