ALTER TYPE "TenantMembershipRole" ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE "TenantMembershipRole" ADD VALUE IF NOT EXISTS 'WAREHOUSE';
ALTER TYPE "TenantMembershipRole" ADD VALUE IF NOT EXISTS 'PICKER';
